const ACCOUNT_ROLE = {
  ADMIN: "ADMIN",
  STAFF: "STAFF",
  CUSTOMER_SUPPORT: "CUSTOMER_SUPPORT",
  DOCTOR: "DOCTOR",
  CUSTOMER: "CUSTOMER",
};

const ACCOUNT_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED",
};

export { ACCOUNT_ROLE, ACCOUNT_STATUS };
