const APPOINTMENT_TYPE = {
  BASIC: "BASIC",
  ADVANCED: "ADVANCED",
};

const APPOINTMENT_STATUS = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  WAITING_ASSIGN: "WAITING_ASSIGN",
  CONFIRMED: "CONFIRMED",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
};

const APPOINTMENT_PRICE = {
  BASIC: 100000,
  ADVANCED: 200000,
};

const PAYMENT_TIMEOUT_MINUTES = 15;

/** Max days in advance a customer can book */
const MAX_BOOKING_ADVANCE_DAYS = 7;

export {
  APPOINTMENT_STATUS,
  APPOINTMENT_TYPE,
  PAYMENT_TIMEOUT_MINUTES,
  MAX_BOOKING_ADVANCE_DAYS,
  APPOINTMENT_PRICE,
};
