const APPOINTMENT_TYPE = {
  BASIC: "BASIC",
  ADVANCED: "ADVANCED",
};

const APPOINTMENT_STATUS = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PAID: "PAID",
  WAITING_ASSIGN: "WAITING_ASSIGN",
  CONFIRMED: "CONFIRMED",
  COMPLETED: "COMPLETED",
};

export { APPOINTMENT_STATUS, APPOINTMENT_TYPE };
