const PAYMENT_STATUS = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  CANCELED: "CANCELED",
};

const PAYMENT_METHOD = {
  PAYOS: "PAYOS",
};

export { PAYMENT_STATUS, PAYMENT_METHOD };
